return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "beautysh",
      "clangd",
      "css-lsp",
      "djlint",
      "emmet-language-server",
      "fixjson",
      "gopls",
      "html-lsp",
      "jdtls",
      "lua-language-server",
      "marksman",
      "nixpkgs-fmt",
      "prettier",
      "pyright",
      "sql-formatter",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "terraform-ls",
      "typescript-language-server",
      "yaml-language-server",
      "yamlfix",
    },
  },
}
